alias ls='ls --color=auto --ignore={NTUSER*,ntuser*}'
alias la='ls -a'
alias ll='ls -lha'
alias grep='grep --color'
alias df='df -h'
alias tmuxchkey='tmux -set-option -ag prefix C-b'
alias tmuxrvkey='tmux -set-option -ag prefix C-t'
